# To specify a subset of chromosomes to operate on, use the --chrs command line
# flag. It is done this way so that we can use the same configuration file here
# in order to parallelize the peak detection per chromosome over the cluster.
genome: mm9
bamfiles:
  wt: "/Users/stavros/cBio/data/aly/bowtie2/mir155-wt.bam"
  ko: "/Users/stavros/cBio/data/aly/bowtie2/mir155-ko.bam"
stranded: TRUE
bandwidth: 35
resize_reads: 32
resize_fix: start
resize_is: min
min_count_event_boundary: 2
trim_pos:
  - 0.02
  - 0.98
trim_neg:
  - 0.02
  - 0.98
bam_tags:
  - X0
  - X1
  - XM
  - XA
# bam.filter needs to parse into an R function. It will take in a
# GappedReads (Granges-like) object and must return the same type of
# object containing only the ranges you want analyzed. for peak identification
# I don't do any filtering
bam_filter: |
  function(x) {
    x
  }
min_width: 24
annotation: "/Users/stavros/cBio/projects/TagSeq/inst/extdata/annotated.genome.mm9.rds"
