genome: hg19
bamfiles:
  bcells.1: "/Users/stavros/cBio/papers/apa-1/data/bams/multimap/clean/bcells-1.bam"
  bcells.2: "/Users/stavros/cBio/papers/apa-1/data/bams/multimap/clean/bcells-2.bam"
peakfile: "annotated-peaks.rds"
chrs:
  # Leave out the chrs section if you want to run on all chromsomes that are
  # defined in the peaks
  - chr21
  - chr22
stranded: TRUE
bam_tags:
  - X0
# bam.filter needs to parse into an R function. It will take in a
# GappedReads (Granges-like) object and must return the same type of
# object containing only the ranges you want analyzed.
# The filter below works with single ended BWA alignments to ensure that only
# uniquely mapping reads are used
bam_filter: |
  function(x) {
    if (!"X0" %in% names(mcols(x))) {
      stop("X0 tag required for BWA-unique filter")
    }
    x[mcols(x)$X0 == 1]
  }
